#!/bin/bash
#############################################################################
sub_a_b_c_usage () {
printf "%s" "\
usage: sub a b c [-h]

  Test a-b-c.  More documentation.

options:

  -h  prints help
"
}
while getopts "h" option
do
  case $option in
    (h)  sub_a_b_c_usage
         exit 0 ;;
    (*)  sub_a_b_c_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################
export SUB_TEST_A_B_C=a_b_c

sub_test_env
