#!/bin/bash
#############################################################################
prototype_a_b_usage () {
printf "%s" "\
usage: prototype a b [-h]

  Test a-b.  More documentation.

options:

  -h  prints help
"
}
while getopts "h" option
do
  case $option in
    (h)  prototype_a_b_usage
         exit 0 ;;
    (*)  prototype_a_b_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################
export PROTOTYPE_TEST_A_B=a_b
export PROTOTYPE_TEST_A_B_C_ENV=a_b
export PROTOTYPE_TEST_A_B_C=a_b

if [ $# -eq 0 ]
then prototype_test_env
else prototype_exec "$@"
fi
