#!/bin/bash
#############################################################################
prototype_y_usage () {
printf "%s" "\
usage: prototype y [-h]

  Test y.  More documentation.

options:

  -h  prints help

"
}
while getopts "h" option
do
  case $option in
    (h)  prototype_y_usage
         exit 0 ;;
    (*)  prototype_y_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################

printf "y\n"
