#!/bin/bash
#############################################################################
prototype_xx_usage () {
printf "%s" "\
usage: prototype xx [-h]

  Test xx.  More documentation.

options:

  -h  prints help

"
}
while getopts "h" option
do
  case $option in
    (h)  prototype_xx_usage
         exit 0 ;;
    (*)  prototype_xx_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################

if [ $# -eq 0 ]
then printf "xx\n"
else prototype_exec "$@"
fi
