#!/bin/bash
#############################################################################
prototype_z_usage () {
printf "%s" "\
usage: prototype z [-h]

  Test z.  More documentation.

options:

  -h  prints help

"
}
while getopts "h" option
do
  case $option in
    (h)  prototype_z_usage
         exit 0 ;;
    (*)  prototype_z_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################

printf "z\n"
