#!/bin/bash

prototype_system_dir="${PROTOTYPE}_SYSTEM_DIR"
prototype_global_dir="${PROTOTYPE}_GLOBAL_DIR"
prototype_var_dir="${PROTOTYPE}_VAR_DIR"

export "${prototype_system_dir}"="${!prototype_system_dir:-/etc/$prototype}"
if [ -e "${!prototype_system_dir}/env" ]
then . "${!prototype_system_dir}/env"
fi

export "${prototype_global_dir}"="${!prototype_global_dir:-$HOME/.$prototype}"
if [ x"${!prototype_global_dir}" != x"${!prototype_system_dir}" ] &&
   [ -e "${!prototype_global_dir}/env" ]
then . "${!prototype_global_dir}/env"
fi

export "${prototype_var_dir}"="${!prototype_var_dir:-/var/$prototype}"

. prototype_setup_home
. prototype_setup_path \
"${!prototype_home}"/libexec       "${!prototype_home}"/plugins/*/libexec \
"${!prototype_global_dir}"/libexec "${!prototype_global_dir}"/plugins/*/libexec \
"${!prototype_system_dir}"/libexec "${!prototype_system_dir}"/plugins/*/libexec
