#!/bin/bash
command=$1
shift 1

if [ -z "$command" ]
then
  printf "no command specified\n" >&2
  exit 1
fi

. prototype_exec_env "$command"

if command -v "${PROTOTYPE_COMMAND}" >/dev/null 2>&1
then
  exec "${PROTOTYPE_COMMAND}" "$@"
else
  printf "unknown command: %s\n" "${PROTOTYPE_COMMAND}" >&2
  exit 1
fi
