#!/bin/bash

prototype_system_env="${PROTOTYPE}_SYSTEM_ENV"
prototype_global_env="${PROTOTYPE}_GLOBAL_ENV"
prototype_var_dir="${PROTOTYPE}_VAR_DIR"

export "${prototype_system_env}"="${!prototype_system_env:-/etc/$prototype}"
if [ -e "${!prototype_system_env}" ]
then . "${!prototype_system_env}"
fi

export "${prototype_global_env}"="${!prototype_global_env:-$HOME/.$prototype}"
if [ x"${!prototype_global_env}" != x"${!prototype_system_env}" ] &&
   [ -e "${!prototype_global_env}" ]
then . "${!prototype_global_env}"
fi

export "${prototype_var_dir}"="${!prototype_var_dir:-/var/$prototype}"

. prototype_setup_home
. prototype_setup_path "${!prototype_home}"/libexec
